<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="CO-IT00600" name="com.tae.training.Tarea2Test" tests="4" failures="0" timestamp="18 oct 2017 01:18:37 GMT" time="0.007" errors="1">
  <testcase name="Test1" time="0.001" classname="com.tae.training.Tarea2Test"/>
  <testcase name="Test2" time="0.001" classname="com.tae.training.Tarea2Test">
    <error type="org.testng.TestNGException" message="
Some DataProvider private java.lang.Object[][] com.tae.training.Tarea2Test.getWords(java.util.ArrayList[][]) parameters unresolved:  at 0 type class [[Ljava.util.ArrayList;
">
      <![CDATA[org.testng.TestNGException: 
Some DataProvider private java.lang.Object[][] com.tae.training.Tarea2Test.getWords(java.util.ArrayList[][]) parameters unresolved:  at 0 type class [[Ljava.util.ArrayList;

	at org.testng.internal.MethodInvocationHelper.getParameters(MethodInvocationHelper.java:176)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:114)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:509)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1308)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1036)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1126)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- Test2 -->
  <testcase name="Test1" time="0.004" classname="com.tae.training.Tarea2Test"/>
  <testcase name="Test1" time="0.001" classname="com.tae.training.Tarea2Test"/>
</testsuite> <!-- com.tae.training.Tarea2Test -->
